name: Health Check

on:
  schedule:
    - cron: 15 23 * * *

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fullstackopen-part11-0unr.onrender.com
          max-attempts: 3
          retry-delay: 10s
