name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install && cd frontend/ && npm install && cd ../
      - name: Check Style
        run: npm run lint
      - name: Build
        run: cd frontend && npm run build && mv build ../
      - name: e2e tests
        uses: cypress-io/github-action@v6
        env:
          MONGO_URI: ${{secrets.MONGO_URI}}
          TEST_MONGO_URI: ${{secrets.TEST_MONGO_URI}}
          SECRET: ${{secrets.SECRET}}
        with:
          command: npm run test:e2e --prefix frontend/
          start: npm run start:test
          wait-on: http://localhost:5000
      - name: Trigger deployment on render
        if: ${{ github.event_name == 'push'  && !contains(toJson(github.event.commits.*.message), '#skip')}}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bumb up the version number
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  discord_notification:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          text: The deployment succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          details: Test Failed! https://github.com/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.event.head_commit.author.username }} broke the build :(
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
